### ISSUE TITLE
NavigationBars 컴포넌트

### ISSUE THREAD

**Issue by aaaz425** [masters2023-project-team05-second-hand/second-hand-max-fe#19]
## Feature
NavigationBar 컴포넌트 UI 구현

### 기존 Button 컴포넌트를 쓸까 vs [NavLink](https://reactrouter.com/en/main/components/nav-link)를 별도로 할까
- NavLink로 결정: 코드가 더 직관적이어서

**Comment by youzysu** [comment]
BrowserRouter를 실제 Routes를 사용하는 곳에 가깝게 두는게 더 좋다고 생각해서 main -> App으로 옮김
