### ISSUE TITLE
MyAccount Page

### ISSUE THREAD

**Issue by aaaz425** [masters2023-project-team05-second-hand/second-hand-max-fe#21]
## Feature
내 계정
### OAuth 회원가입/로그인/로그아웃
- [x] #24
- [x] #23
- [x] #22
- [x] Access Token 관리 (refreshToken으로 재발급)

### 유저 정보 설정
- [x] #33 
- [x] #34 
- [x] #35

**Comment by youzysu** [comment]
## 현재 상황
- 로그인 response로만 유저의 addresses를 받아오고 이걸 웹 스토리지에 저장해두고 있어서 서버에서 최신값으로 받아오려면 로그인을 다시 하는수밖에 없음.
- 현재 방식에서 로그인 상태 유지하면서도 addresses 동기화하려면? beforeunload 할 때 웹 스토리지에 있는 addresses setItem으로 직접 관리해야 함 현재 선택된 id에 해당하는 마을 isLastVisited true까지 설정해줘야 함.. 😇

**Comment by youzysu** [comment]
## AccessToken
- accessToken 만료 ? (refreshToken 만료 ? 로그아웃 처리 : accessToken 재발급) : 로그인 처리

### 토큰 관리 방식
- 현재 웹 스토리지에 모두 올려놓고 사용
- 실제 현업에서는 refreshToken 브라우저 쿠키에 저장 & accessToken은 클라이언트 상태(메모리에 올려서, 데이터)로만 관리함

## Token Refresh 로직
- response intercepter에서 토큰 만료 관련 상태 코드 받으면 refresh 재발급 요청(/api/reissue-access-token)
- 새로 받은 토큰으로 재요청
