### ISSUE TITLE
kakao OAuth 기능 구현

### ISSUE THREAD

**Issue by aaaz425** [masters2023-project-team05-second-hand/second-hand-max-fe#23]
## Feature
kakao OAuth 기능 구현

**Comment by youzysu** [comment]
## 고민
## Register를 별도 페이지로 관리하는 것에 대한 고민

### 1. MyAccount와 별도 페이지로 관리하기
- 반드시 위치 추가 하도록 해야 함
- 프론트에서 default로 설정해두고 유저가 직접 선택하지 않아도 완료 버튼 클릭할 때/페이지 이탈할 때도 동네 설정 요청 필요

### 2. MyAccount 하위 컴포넌트로 구성하기
- 기존 유저는 해당 페이지에 접근하지 못하도록 해야함
- register 페이지는 최초 로그인 시에만 접근 가능하도록 할 수 있는 방법? 

### 선택 방법
- register 페이지 접근 시 유저 동네 리스트가 있으면 setting으로 라우팅 처리하기?

**Comment by youzysu** [comment]
# 카카오 OAuth 참고자료
- https://developers.kakao.com/docs/latest/ko/kakaologin/rest-api
- https://devhaks.github.io/2019/05/31/oauth2/
- https://developers.kakao.com/docs/latest/ko/kakaologin/common
