### ISSUE TITLE
상품 상세 페이지 채팅방 버튼 기능

### ISSUE THREAD

**Issue by youzysu** [masters2023-project-team05-second-hand/second-hand-max-fe#70]
### 판매자
- [x]  가장 오른쪽에 [대화 중인 채팅방 + 카운터]가 표시되도록 하며, 해당 버튼을 누르면 해당 상품과 관련한 채팅방이 목록으로 보여지도록 한다.
- [x]  채팅한 내역이 없는 경우 [대화 중인 채팅방]버튼만 표시되며, 해당 버튼을 누르면 ‘채팅한 이웃이 없습니다’라는 토스트 메세지를 받는다.

### 구매자
- [x]  [채팅하기] 버튼을 누르면 판매자에게 연락할 수 있는 채팅 상세 화면으로 즉시 이동한다.
- [ ]  첫 메세지를 보내기 전까지, 채팅방이 실제로 생성되지는 않도록 한다.

**Comment by aaaz425** [comment]
> 첫 메세지를 보내기 전까지, 채팅방이 실제로 생성되지는 않도록 한다.

채팅 기능을 붙여봐야 알 수 있을 듯 합니다

api가 나와야 navigate path에 어떤 정보가 들어갈지 확실해 질 것 같습니다~
